<div class="right-panel" style="padding: 0;"><div class="wrap">
<div class="form">
	<div class="annotation">name=grabber|successUrl=/admin/grabber</div>
	<?if($this->grabber){?>
	<span class="formItem"><input type="hidden" name="id" value="<?=$this->grabber->id;?>" /></span>
	<?}?>
	<h2><?=$this->grabber->site;?></h2>
	<table>
		<tr class="formItem">
			<td>
				<div class="label-text">С какого адреса отправлять</div>
				<div class="annotation">required=true|error.required=Обязательно к заполнению</div>
				<input type="text" class="text" name="email" value="<?if($this->grabber) echo $this->grabber->email;?>"/>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td>
				<div class="label-text">На какой адрес отправлять</div>
				<div class="annotation">required=true|error.required=Обязательно к заполнению</div>
				<input type="text" class="text" name="email2" value="<?if($this->grabber) echo $this->grabber->email2;?>"/>
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
</div>
</div></div>