<table class="all">
	<tr>
		<td class="left">
			<h1><?=$this->pageTitle; ?></h1>
		</td>
		<td class="right" nowrap="nowrap">
			<?if(count($this->buttons) > 0) { ?>
			<table class="items">
				<tr>
					<?
					for($i = 0; $i < count($this->buttons); $i++){
						$button = $this->buttons[$i];
						?>
						<td><?include 'buttons/'.$button->type.'.phtml'; ?></td>
					<?}?>
				</tr>
			</table>
			<?} ?>
		</td>
	</tr>
</table>