<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Вставка изображений</title>
	<script language="javascript" src="/admin/js/jquery.js" type="text/javascript"></script>
	<script language="javascript" src="/admin/js/swfobject.js" type="text/javascript"></script>
	<script type="text/javascript" src="/admin/js/XMLParser.js" charset="UTF-8"></script>
	<script type="text/javascript" src="/admin/js/Form.js" charset="UTF-8"></script>
	<script language="javascript" src="/admin/js/common.js" type="text/javascript"></script>
	<script type="text/javascript" src="/admin/editor/tiny_mce_popup.js"></script>
	<script type="text/javascript" charset="UTF-8">
		formUrl = "/admin/form/";
	</script>
	<script type="text/javascript">
		var folder = "/media/";
		onInit(function(){
			var so = new SWFObject("/admin/flash/uploader.swf", "editoruploader", "250", "25", "9");
			so.addParam("wmode", "opaque");
			so.addVariable("url", "/admin/editor/upload/?atmsessid=<?=$this->sessionid; ?>");
			so.addVariable("onError", "onError");
			so.addVariable("dataid", "1");
			so.addVariable("multi", "true");
			so.addVariable("onOk", "onUpload");
			so.write("uploader");
		});
		function onError(t){
			document.location.href = "/admin/editor/list";
		}
		function onUpload(data){
			document.location.href = "/admin/editor/list";
		}
		var sel = null;
		var selW = 0;
		var selH = 0;
		var selA = '';
		onInit(function(){
			var ed = tinyMCEPopup.editor, dom = ed.dom, n = ed.selection.getNode();
			if (n && n.nodeName == 'IMG') {
				sel = ed.dom.getAttrib(n, 'src');
				if(ed.dom.getAttrib(n, 'width'))
					selW = parseInt(ed.dom.getAttrib(n, 'width'));
				if(ed.dom.getAttrib(n, 'height'))
					selH = parseInt(ed.dom.getAttrib(n, 'height'));
				if(ed.dom.getAttrib(n, 'align'))
					selA = ed.dom.getAttrib(n, 'align');
			}
			jq(".container div").each(function(i, item){
				item = jq(item);
				var addr = "/media/" + jq("span", item).html();
				if(addr == sel){
					jq(".pic-block").show();
					jq(".link input").val(sel);
					loadImage(folder + jq("span", item).html());
				}
				item.click(function(){
					jq(".pic-block").show();
					jq(".link input").val("/media/" + jq("span", item).html());
					loadImage(folder + jq("span", item).html());
				});
				jq(".del", item).click(function(){
					jq.post("/admin/editor/delete", {name:jq("span", item).html()}, function(){
						item.remove();
					});
					return false;
				});
			});
		});
		var img = null;
		var name = "";
		function loadImage(n){
			name = n;
			img = new Image();
			img.onload = onLoad;
			img.src = name;
		}
		
		function onLoad(){
			var h = 0, w =0;
			var iW = img.width;
			var iH = img.height;
			var iA = '';
			if(img.src.indexOf(sel) >= 0)
			{
				if(selW > 0)
					iW = selW;
				if(selH > 0)
					iH = selH;
				iA = selA;
			}
			jq("[name=align]").val(iA);
			jq("[name=width]").val(iW);
			jq("[name=height]").val(iH);
			if(img.width < img.height){
				h = 200;
				w = Math.round(200 * img.width / img.height);
			}else{
				w = 200;
				h = Math.round(200 * img.height / img.width);
			}
			jq(".frame").attr("width", w);
			jq(".frame").attr("height", h);
			jq(".frame").attr("src", name);
			jq(".frame").css({display:"block"});
		}
		
		var ImageDialog = {
			init : function(ed) {
				var ed = tinyMCEPopup.editor, dom = ed.dom, n = ed.selection.getNode();
				jq(".past").click(function(){
					if(img == null){
						tinyMCEPopup.close();
						return false;
					}
					var opts = {src:name, width:jq("[name=width]").val(), height:jq("[name=height]").val(), align: jq("[name=align]").val()};
					if (n && n.nodeName == 'IMG') {
						ed.dom.setAttribs(n, opts);
					}else{
						ed.execCommand('mceInsertContent', false, '<img id="__mce_tmp" />', {});
						ed.dom.setAttribs('__mce_tmp', opts);
						ed.dom.setAttrib('__mce_tmp', 'id', '');
					}
					tinyMCEPopup.close();
				});
				jq(".cancel").click(function(){
					tinyMCEPopup.close();
				});
			}
		};
		tinyMCEPopup.onInit.add(ImageDialog.init, ImageDialog);
	</script>
	<style>
		html, body{width:100%;height:100%;padding: 0;margin: 0;}
		table, tr, td{border-collapse: collapse;padding: 0;margin: 0;font-size: 13px;color:#333;vertical-align: top;}
		img.del{width:12px;height:12px;background:url('/admin/images/publish_x.png') no-repeat;_background:none;filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/admin/images/publish_x.png', sizingMethod='noscale');cursor: pointer;}
	</style>
</head>
<body id="advimage" style="background-color: #f1f3f5;">
	<table class="cont">
		<tr>
			<td style="padding:5px 0px 0px 5px;">
				<div id="uploader"></div>
			</td>
			<td></td>
		</tr>
		<tr>
			<td style="padding: 5px">
				<div style="width:500px;height:300px;overflow:auto;border:1px solid black;" class="container">
					<?
					foreach($this->files as $file)
					{?>
						<div style="padding:2px 5px;background-color: #ccc;border-top:1px solid #fff;border-top:1px solid #fff;cursor: pointer;">
							<img src="/admin/images/spacer.gif" width="12" height="12" class="del" alt="Удалить" /> &nbsp;
							<span><?=$file?></span>
						</div>
					<?}
					?>
				</div>
			</td>
			<td>
				<img class="frame" src="/admin/images/spacer.gif" style="display:none;padding:5px 0 0 0;" width="" height="" />
				<div class="pic-block" style="display: none;">
					<div style="padding-top:15px;height:25px;" class="link">
						Ссылка на файл:<br />
						<input type="text" value="" style="width:200px;"/>
					</div>
					<div style="padding-top:15px;height:25px;">
						ширина: <input type="text" name="width" style="width:30px;"/> высота: <input type="text" name="height" style="width:30px;"/>
					</div>
					<div style="padding-top:5px;height:25px;">
						выравнивание: 
						<select name="align">
							<option value="">Нет</option>
							<option value="left">Слева</option>
							<option value="right">Справа</option>
							<option value="top">По верху</option>
							<option value="bottom">По низу</option>
							<option value="middle">По центру</option>
						</select>
					</div>
				</div>
			</td>
		</tr>
	</table>
	<img src="/admin/images/past.png" style="margin:0px 10px 0px 5px;cursor: pointer;" class="past" /><img src="/admin/images/cancel.png" class="cancel" style="cursor:pointer;"/>
</body>
</html>