<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Вставка изображений</title>
	<script language="javascript" src="/admin/js/jquery.js" type="text/javascript"></script>
	<script language="javascript" src="/admin/js/swfobject.js" type="text/javascript"></script>
	<script type="text/javascript" src="/admin/js/datepicker.js"></script>
	<script language="javascript" src="/admin/js/jquery-ui.js" type="text/javascript"></script>
	<script type="text/javascript" src="/admin/js/XMLParser.js" charset="UTF-8"></script>
	<script type="text/javascript" src="/admin/js/Form.js" charset="UTF-8"></script>
	<script language="javascript" src="/admin/js/common.js" type="text/javascript"></script>
	<script type="text/javascript" src="/admin/editor/tiny_mce_popup.js"></script>
	<script type="text/javascript" charset="UTF-8">
		formUrl = "/admin/form/";
	</script>
	<script type="text/javascript">
		var folder = "/media/";
		onInit(function(){
			var so = new SWFObject("/admin/flash/uploader.swf", "editoruploader", "250", "25", "9");
			so.addParam("wmode", "opaque");
			so.addVariable("url", "/admin/editor/upload/?PHPSESSID=<?echo Template::get("sessionid"); ?>");
			so.addVariable("onError", "onError");
			so.addVariable("dataid", "1");
			so.addVariable("multi", "true");
			so.addVariable("onOk", "onUpload");
			so.write("uploader");
		});
		function onError(t){
			document.location.href = "/admin/editor/list";
		}
		function onUpload(data){
			document.location.href = "/admin/editor/list";
		}
		onInit(function(){
			jq(".container div").each(function(i, item){
				item = jq(item);
				item.click(function(){
					loadImage(folder + item.html());
				});
			});
		});
		var img = null;
		var name = "";
		function loadImage(n){
			name = n;
			img = new Image();
			img.onload = onLoad;
			img.src = name;
		}
		
		function onLoad(){
			var h = 0, w =0;
			if(img.width < img.height){
				h = 200;
				w = Math.round(200 * img.width / img.height);
			}else{
				w = 200;
				h = Math.round(200 * img.height / img.width);
			}
			jq(".frame").attr("width", w);
			jq(".frame").attr("height", h);
			jq(".frame").attr("src", name);
			jq(".frame").css({display:"block"});
		}
		
		var ImageDialog = {
			init : function(ed) {
				var ed = tinyMCEPopup.editor, dom = ed.dom, n = ed.selection.getNode();
				jq(".past").click(function(){
					if(img == null){
						tinyMCEPopup.close();
						return false;
					}
					if (n && n.nodeName == 'IMG') {
						ed.dom.setAttribs(n, {src:name});
					}else{
						ed.execCommand('mceInsertContent', false, '<img id="__mce_tmp" />', {});
						ed.dom.setAttribs('__mce_tmp', {src:name});
						ed.dom.setAttrib('__mce_tmp', 'id', '');
					}
					tinyMCEPopup.close();
				});
				jq(".cancel").click(function(){
					tinyMCEPopup.close();
				});
			}
		};
		tinyMCEPopup.onInit.add(ImageDialog.init, ImageDialog);
	</script>
	<style>
		html, body{width:100%;height:100%;padding: 0;margin: 0;}
		table, tr, td{border-collapse: collapse;padding: 0;margin: 0;font-size: 13px;color:#333;vertical-align: top;}
	</style>
</head>
<body id="advimage" style="background-color: #f1f3f5;">
	<table class="cont">
		<tr>
			<td style="padding:5px 0px 0px 5px;">
				<div id="uploader"></div>
			</td>
			<td></td>
		</tr>
		<tr>
			<td style="padding: 5px">
				<div style="width:300px;height:200px;overflow:auto;border:1px solid black;" class="container">
					<?
					$files = Template::get("files");
					for($i = 0; $i < count($files); $i++)
					{?>
						<div style="padding:2px 5px;background-color: #ccc;border-top:1px solid #fff;border-top:1px solid #fff;cursor: pointer;"><?echo $files[$i]; ?></div>
					<?}
					?>
				</div>
			</td>
			<td>
				<img class="frame" src="" style="display:none;padding:5px 0 0 0;" width="" height="" />
			</td>
		</tr>
	</table>
	<img src="/admin/images/past.png" style="margin:0px 10px 0px 5px;cursor: pointer;" class="past" /><img src="/admin/images/cancel.png" class="cancel" style="cursor:pointer;"/>
</body>
</html>