<script>
	onInit(function(){
		jq("#saveformbutton").click(function(){
			var f = jq(".form");
			if(f.length == 0 || f.length > 1){
				alert("На странице отсутствует форма или их 2");
				return false;
			}
			Form.forms[f.attr("id")].submit()
			return false;
		});
	});
</script>
<?$title =$button->message;?>
<a href="" title="<? echo $title ?>" id="saveformbutton">
	<?if(isset($button->data[img])){ ?>
		<img src="<? echo $button->data[img]; ?>" alt="<? echo $title ?>" align="middle" class="png" width="32" height="32"/><br />
	<?}else{ ?>
		<img src="images/save_f2.png" alt="<? echo $title; ?>" align="middle" class="png" width="32" height="32"/><br />
	<?} ?>
	<? echo $title; ?>
</a>