<?
$user = new User(Template::get("user"));
$roles = Template::get("roles");
?>
<div class="form form-panel" id="userform">
	<div class="annotation">name=users,successUrl=/admin/users</div>
	<span class="formItem"><input type="hidden" name="id" value="<? echo $user->id;?>" /></span>
	<table>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,error.required=Обязательно к заполнению,error.not.unique=E-mail уже существует,type=email</div>
				E-mail:
			</td>
			<td>
				<input class="text" type="text" name="email" value="<?echo $user->email; ?>" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">error.required=Обязательно к заполнению</div>
				Новый пароль:
			</td>
			<td>
				<input class="text" type="password" name="password" value="" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">validate=comparePasswords,error.required=Обязательно к заполнению,error.not.valid=Не совпадает</div>
				Подтверждение пароля:
			</td>
			<td>
				<input class="text" type="password" name="password2" value="" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">type=checkbox</div>
				Заблокирован:
			</td>
			<td>
				<?
					$str = '';
					if($user->isblocked == 1)
						$str = "checked='checked'";
				?>
				<input name="isblocked" type="checkbox" <? echo $str;?>/>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">value=getRoles,name=roles,required=true</div>
				Роли пользователя:
			</td>
			<td>
				<?
				for($i = 0; $i < count($roles); $i++)
				{
					$checked = "";
					for($j = 0; $j < count($user->roles); $j++)
					{
						if($user->roles[$j]->id == $roles[$i]->id)
							$checked = "checked='checked'";
					}
				?>
					<input type="checkbox" value="<?echo $roles[$i]->id;?>" id="role<?echo $roles[$i]->id;?>" <?echo $checked; ?> /> <label for="role<?echo $roles[$i]->id; ?>"><?echo $roles[$i]->name;?></label><br />
				<?}?>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript">
	function comparePasswords(field, fields){
		var v = jq("[@name=password]").val();
		if(v != "" && jq("[@name=password2]").val() != v)
			field.addError("not.valid");
	}
	function getRoles(field){
		var ids = "";
		jq("input:checked", field).each(function(i, item){
			item = jq(item);
			if(i > 0)
				ids +=",";
			ids += item.attr("id").replace("role", "");
		});
		return ids;
	}
</script>