<?
$gallery = new Gallery(Template::get("gallery"));
?>
<script type="text/javascript">
	function onGallerySave(d, data){
		showOk();
	}
	function getUrl(item){
		var url = jq.trim(jq("input", item).val());
		if(url.length < 1)
			return url;
		if(url.charAt(0) == '/')
			url = url.substr(1, url.length);
		return url;
	}
</script>
<div class="form" id="galleryform">
	<div class="annotation">name=photo/gallery,onSuccess=onGallerySave</div>
	<span class="formItem"><input type="hidden" name="id" value="<? echo $gallery->id;?>" /></span>
	<table>
		<tr class="formItem">
			<td class="label">
				Название фотогалереи
			</td>
			<td>
				<input class="text" type="text" name="title" value="<? echo stripslashes($gallery->title);?>" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,value=getUrl,error.required=Обязательно к заполнению,error.not.unique=URL-адрес уже существует</div>
				URL на сайте
			</td>
			<td>
				<input type="text" name="url" value="<? echo stripslashes($gallery->url);?>" class="text" />
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<table>
		<tr class="formItem">
			<td colspan="2">
				<div class="label-text">Описание фотогалереи</div>
				<?php if($presets->useeditor == 1){?>
				<div class="annotation">type=richtext</div>
				<textarea name="description" class="richtext" id="richeditor_description" style="height:250px;width:100%;"><? echo stripslashes($gallery->description);?></textarea>
				<?php }else{?>
				<textarea name="description" id="richeditor_description" style="height:250px;width:100%;"><? echo stripslashes($gallery->description);?></textarea>
				<?php }?>
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<?php
		$returnUrl = '/admin/photo/edit/'.$gallery->id;;
		$deleteUrl = '/admin/photo/photo/delete';
		$uploadUrl = '/admin/photo/photo/upload';
		include 'templates/photo_uploader.phtml';
	?>
</div>