<script type="text/javascript">
	function getUrl(item){
		var url = jq.trim(jq("input", item).val());
		if(url.length < 1)
			return url;
		if(url.charAt(0) == '/')
			url = url.substr(1, url.length);
		return url;
	}
</script>
<?
$project = new Project(Template::get("project"));
$category = Template::get("category");
$categories = Template::get("categories");
?>
<div class="form" id="itemform">
	<div class="annotation">name=projects,successUrl=/admin/projects/<?echo $category->url; ?></div>
	<span class="formItem"><input type="hidden" name="id" value="<? echo $project->id;?>" /></span>
	<table>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,value=getUrl,error.required=Обязательно к заполнению,error.not.unique=URL-адрес уже существует</div>
				URL на сайте
			</td>
			<td>
				<input type="text" name="url" value="<? echo $project->url;?>" class="text" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td colspan="2">
				<div class="label-text">Название</div>
				<div class="annotation">required=true,error.required=Обязательно к заполнению,error.not.valid=не верно</div>
				<textarea name="name" style="height:30px;"><? echo stripslashes($project->name);?></textarea>
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<table>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,type=select</div>
				Категория
			</td>
			<td>
				<select name='category'>
					<?
						for($i = 0; $i < count($categories); $i++){
							if($categories[$i]->id == $project->category){?>
								<option value="<?echo $categories[$i]->id; ?>" selected="selected"><?echo $categories[$i]->name; ?></option>
							<?}else{?>
								<option value="<?echo $categories[$i]->id; ?>"><?echo $categories[$i]->name; ?></option>
							<?}
						}
					?>
				</select>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">Дата:</td>
			<td>
				<div class="annotation">type=datepicker,name=date</div>
				<input type="text" value="<?echo date('d-m-Y', strtotime($project->date)); ?>" class="text"/>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">Опубликован:</td>
			<td>
				<?
					$str = '';
					if($project->published == 1)
						$str = "checked='checked'";
				?>
				<div class="annotation">type=checkbox</div>
				<input name="published" type="checkbox" <? echo $str;?>/>
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<table>
		<tr class="formItem">
			<td>
				<div class="label-text">Текст</div>
				<?php if($presets->useeditor == 1){?>
				<div class="annotation">type=richtext</div>
				<textarea name="description" id="richeditor_text" class="richtext" style="height:400px;width:100%;"><? echo stripslashes($project->description);?></textarea>
				<?php }else{?>
				<textarea name="description" id="richeditor_text" style="height:400px;width:100%;"><? echo stripslashes($project->description);?></textarea>
				<?php }?>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem" style="display: none;">
			<td>
				<div class="label-text">Теги</div>
				<textarea name="shortdescription" style="height:150px;"><? echo stripslashes($project->shortdescription);?></textarea>
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<td class="label">Изображение:</td>
			<td>
				<?php 
				$image = $project->image;
				$uploadUrl = "/admin/projects/image/upload";
				$editUrl = "/admin/photo/image/edit?url=/admin/projects/".$category->url.'/edit/'.$project->id.'&id=';
				$deleteUrl = "/admin/projects/image/delete/";
				$dataid = $project->id;
				$dopVars = array('project'=>$project->id);
				include 'templates/image_uploader.phtml';
				?>
			</td>
		</tr>
	</table>
	<?php
		$gallery = $project->gal;
		$returnUrl = '/admin/projects/'.$category->url.'/edit/'.$project->id;;
		$deleteUrl = '/admin/projects/photo/delete';
		$uploadUrl = '/admin/projects/photo/upload';
		$dopVars = array('project'=>$project->id);
		include 'templates/photo_uploader.phtml';
	?>
</div>