<?$category = Template::get("category");?>
<script type="text/javascript">
	function getUrl(item){
		var url = jq.trim(jq("input", item).val());
		if(url.length < 1)
			return url;
		if(url.charAt(0) == '/')
			url = url.substr(1, url.length);
		return url;
	}
	function onCategorySave(d, data){
		showOk();
	}
</script>
<div class="form" id="categoryform">
	<div class="annotation">name=catalog/categories,onSuccess=onCategorySave</div>
	<span class="formItem"><input type="hidden" name="id" value="<? echo $category->id;?>" /></span>
	<table>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,error.required=Обязательно к заполнению</div>
				Название
			</td>
			<td>
				<input class="text" type="text" name="name" value="<? echo stripslashes($category->name);?>" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,value=getUrl,error.required=Обязательно к заполнению,error.not.unique=URL-адрес уже существует</div>
				URL на сайте
			</td>
			<td>
				<input type="text" name="url" value="<? echo stripslashes($category->url);?>" class="text" />
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<table>
		<tr class="formItem">
			<td colspan="2">
				<div class="label-text">Описание</div>
				<?php if($presets->useeditor == 1){?>
				<div class="annotation">type=richtext</div>
				<textarea name="description" class="richtext" id="description" style="height:400px;width:100%;"><? echo stripslashes($category->description);?></textarea>
				<?php }else{?>
				<textarea name="description" id="description" style="height:400px;width:100%;"><? echo stripslashes($category->description);?></textarea>
				<?php }?>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr>
			<td colspan="2" class="checks">
				<div class="formItem">
					<div class="annotation">type=checkbox</div>
					<?
						$str = '';
						if($category->published == 1)
							$str = "checked='checked'";
					?>
					Категория опубликована: <input name="published" type="checkbox" <? echo $str;?>/>
				</div>
           </td>
		</tr>
	</table>
</div>