<?
$atoms = array();
if(Template::get("article")){
	$article = Template::get("article");
	$atoms = explode(".", $article->code);
}
if(Template::get("okArticle")){
	$article = Template::get("okArticle");
	$atoms = explode(".", $article->code);
}
	
function printArticles($parent = 0, $atoms)
{
	$articles = Template::get("articles");
	if(count($articles) == 0)
		return;
	$art = Template::get("article");
	foreach($articles[$parent] as $article)
	{	
		$inPath = false;
		if($atoms[0] == $article->code && $atoms[0] != $art->code){
			$a = $atoms[0];
			$inPath = true;
			$atoms = ArrayUtil::splice($atoms, 1);
			$atoms[0] = $a.".".$atoms[0];
		}
	?>
		<table class="item" id="article<? echo $article->id; ?>">
			<tr>
				<td class="plus" id="plus<? echo $article->id; ?>">
					<?if(count($articles[$article->id]) > 0){
						$minusStyle = $plusStyle = "";
						if($inPath)
							$plusStyle = "display:none;";
						else 
							$minusStyle = "display:none;";
					?>
					<img src="/admin/images/plus.gif" onclick="Article.plus(<?echo $article->id; ?>);" alt=""  width="9" height="9" style="<? echo $plusStyle; ?>"/>
					<img src="/admin/images/minus.gif" onclick="Article.minus(<?echo $article->id; ?>);"  alt="" width="9" height="9" style="<?echo $minusStyle; ?>"/>
					<?}?>
				</td>
				<td class="title"><a id="a<?echo $article->id; ?>" href="/admin/article/edit/<? echo $article->url; ?>"><? echo stripslashes($article->name); ?></a></td>
				<td class="buttons">
					<table><tr>
						<td><a href="/admin/article/new/<? echo $article->id; ?>" title="Добавить подстатью"><img src="/admin/images/add.gif" width="12" height="12" alt="Добавить подстраницу"/></a></td>
						<td>
							<?
								$publStyle = $unpublStyle = "";
								if($article->published == 1)
									$unpublStyle = "display:none;";
								else 
									$publStyle = "display:none;";
							?>
							<img src="/admin/images/spacer.gif" onclick="Article.publish(<?echo $article->id; ?>);" class="publ" style="<?echo $publStyle; ?>" width="12" height="12" alt="Опубликовать" />
							<img src="/admin/images/spacer.gif" onclick="Article.unpublish(<?echo $article->id; ?>);" style="<?echo $unpublStyle; ?>" class="unpubl" width="12" height="12" alt="Скрыть" />
						</td>
						<td><img src="/admin/images/spacer.gif" onclick="Article.del(<?echo $article->id; ?>);" class="del" width="12" height="12" alt="Удалить" /></td>
						<td><img src="/admin/images/spacer.gif" onclick="Article.down(<?echo $article->id; ?>);" class="down" width="12" height="12" /></td>
						<td class="count"><? echo $article->ord; ?></td>
						<td><img src="/admin/images/spacer.gif" onclick="Article.up(<?echo $article->id; ?>);" class="up" width="12" height="12" /></td>
					</tr></table>
				</td>
			</tr>
		</table>
		<?if(count($articles[$article->id]) > 0){
			$vis = "";
			if($inPath)
				$vis = "display:block;";
			?>
			<table class="sub" id="sub<?echo $article->id; ?>" style="<?echo $vis; ?>">
				<tr>
					<td class="sub-td"><?printArticles($article->id, $atoms); ?></td>
				</tr>
			</table>
		<?} ?>
	<?}
}
?>
<table class="article-content">
	<tr>
		<td class="left-panel">
			<table class="all">
				<tr>
					<td class="all">
						<?printArticles(0, $atoms);?>
						<div class="create"><img src="/admin/images/add.gif" width="12" height="12" alt="Добавить статью" style="position: relative;top:3px;"/> <a href="/admin/article/new">Новая страница</a></div>
					</td>
				</tr>
			</table>
		</td>
		<td class="right-panel">
			<?if(Template::get("article")){ ?>
			<div class="ok-panel">
				Изменения сохранены
			</div>
			<div class="wrap">
				<?include 'form.phtml';?>
			</div>
			<?} ?>
		</td>
	</tr>
</table>