<?
$article = new Article(Template::get("article"));
?>
<script type="text/javascript">
	function onArticleSave(d, data){
		showOk();
	}
	function getUrl(item){
		var url = jq.trim(jq("input", item).val());
		if(url.length < 1)
			return url;
		if(url.charAt(0) == '/')
			url = url.substr(1, url.length);
		return url;
	}
</script>
<?
if(Config::get("useLinks"))
	include 'links.phtml';
?>
<div class="form" id="articleform">
	<div class="annotation">name=article,onSuccess=onArticleSave</div>
	<span class="formItem"><input type="hidden" name="id" value="<? echo $article->id;?>" /></span>
	<table>
		<tr>
			<td colspan="2" class="checks">
			<table>
				<tr>
				<td class="label"><span class="formItem" style="display: none;"><input type="hidden" name="def" value="false" /></span></td>
				<!-- 
				<td><div class="formItem">
					<div class="annotation">type=checkbox</div>
					<?
						$str = '';
						if($article->def == 1)
							$str = "checked='checked'";
					?>
					Главная страница: <input name="def" type="checkbox" <? echo $str;?>/>
				</div></td> -->
            	<td><div class="formItem">
					<div class="annotation">type=checkbox</div>
					<?
						$str = '';
						if($article->published == 1)
							$str = "checked='checked'";
					?>
					Опубликована: <input name="published" type="checkbox" <? echo $str;?>/>
				</div></td>
            	<td><div class="formItem">
					<div class="annotation">type=checkbox</div>
					<?
						$str = '';
						if($article->flag1 == 1)
							$str = "checked='checked'";
					?>
					Узнай больше:) <input name="flag1" type="checkbox" <? echo $str;?>/>
            	</div></td>
            	<td><div class="formItem">
					<div class="annotation">type=checkbox</div>
					<?
						$str = '';
						if($article->flag2 == 1)
							$str = "checked='checked'";
					?>
					Будет в подменю <input name="flag2" type="checkbox" <? echo $str;?>/>
            	</div></td>
            	<!-- 
            	<td><div class="formItem">
					<div class="annotation">type=checkbox</div>
					<?
						$str = '';
						if($article->flag2 == 1)
							$str = "checked='checked'";
					?>
					Флаг2: <input name="flag2" type="checkbox" <? echo $str;?>/>
            	</div></td> -->
            	</tr></table>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,error.required=Обязательно к заполнению</div>
				Имя страницы
			</td>
			<td>
				<input class="text" type="text" name="name" value="<? echo stripslashes($article->name);?>" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">
				<div class="annotation">required=true,value=getUrl,error.required=Обязательно к заполнению,error.not.unique=URL-адрес уже существует</div>
				Имя на сайте (латиницей)
			</td>
			<td>
				<input type="text" name="url" value="<? echo stripslashes($article->url);?>" class="text" />
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr>
			<td class="label">Изображение:</td>
			<td>
				<?php 
				$image = $article->image;
				$uploadUrl = "/admin/article/image/upload";
				$editUrl = '/admin/photo/image/edit?url=/admin/article/edit/'.$article->id.'&id=';
				$deleteUrl = "/admin/article/image/delete/";
				$dataid = $article->id;
				include 'templates/image_uploader.phtml';
				?>
			</td>
		</tr>
	</table>
	<table>
		<tr class="formItem">
			<td colspan="2">
				<div class="label-text">Текст</div>
				<?php if($presets->useeditor == 1){?>
				<div class="annotation">type=richtext</div>
				<textarea name="text" id="richeditor_text" class="richtext" style="height:400px;width:100%;"><? echo stripslashes($article->text);?></textarea>
				<?php }else{?>
				<textarea name="text" id="richeditor_text"style="height:400px;width:100%;"><? echo stripslashes($article->text);?></textarea>
				<?php }?>
				<div class="errorMessage"></div>
			</td>
		</tr>
	</table>
	<table>
		<tr class="formItem">
			<td class="label">Заголовок страницы (title)</td>
			<td>
				<textarea name="title" style="height:30px;"><? echo stripslashes($article->title);?></textarea>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">Ключевые слова страницы</td>
			<td>
				<textarea name="metakeys" style="height:40px;"><? echo stripslashes($article->metakeys);?></textarea>
				<div class="errorMessage"></div>
			</td>
		</tr>
		<tr class="formItem">
			<td class="label">Описание страницы</td>
			<td>
				<textarea name="descr" style="height:40px;"><? echo stripslashes($article->descr);?></textarea>
				<div class="errorMessage"></div>
			</td>
		</tr>	
		<tr class="formItem">
			<td class="label">Ссылка на другой url</td>
			<td>
				<input type="text" name="otherurl" value="<? echo stripslashes($article->otherurl);?>" class="text" />
				<div class="errorMessage"></div>
			</td>
		</tr>		
	</table>
	<?if(!Config::get("article_photo")){
		$gallery = $article->gal;
		$returnUrl = '/admin/article/edit/'.$article->url;
		$deleteUrl = '/admin/article/photo/delete';
		$uploadUrl = '/admin/article/photo/upload';
		include 'templates/photo_uploader.phtml';
	}
	?>
</div>