<?php
	include ('macros.phtml');
	$template = Template::getAll();
	$presets = Template::get('presets');
	$partName = $template['partName'];
	if($partName == "default")
		$partName = "index";
?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?echo Dictionary::get("title"); ?> - <?echo $template["title"];?></title>
	<meta name="keywords" content="<?echo $template["keywords"];?>" />
	<meta name="description" content="<?echo $template["description"];?>" />
	<base href="http://<?echo $template["server"];?>/admin/"/>
	<link href="/admin/compress/css?scripts=style,jcrop,ui/core,ui/accordion,ui/datepicker,ui/dialog,ui/progressbar,ui/resizable,ui/slider,ui/tabs,ui/theme" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="/admin/compress/js?scripts=jquery,swfobject,jquery-ui,datepicker-ru,XMLParser,Form,common,menu,admin"></script>
	<script type="text/javascript" src="editor/tiny_mce_gzip.js"></script>
</head>
<body>
<div class="trace-panel"></div>
<table class="main">
	<tr>
		<td class="top1">
			<? echo $template["server"]." - ".Dictionary::get("title"); ?>
			<?if(count($template['languages']) > 1){ ?>
			<select>
				<?
				if(count($template['languages']) > 1){
					for($i = 0; $i < count($template['languages']); $i++){
						$sel = "";
						if($template['languages'][$i] == $template['currentLanguage'])
							$sel = "selected='selected'";
						?>
						<option value="<?echo $template['languages'][$i]; ?>" <?echo $sel; ?>><?echo Dictionary::get("lang.".$template['languages'][$i]); ?></option>
					<?}
				}
				?>
			</select>
			<?} ?>
		</td>
	</tr>
	<tr>
		<td class="menu">
			<table>
				<tr>
					<?
					for($i = 0; $i < count($template['menu']); $i ++)
					{
						$item = $template['menu'][$i];
						?>
						<td nowrap="nowrap">
							<?
							if($item->url != null){
							?>
								<a href="/admin<?echo $item->url; ?>" class="item"><?echo $item->name; ?></a>
							<?}else{ ?>
								<a class="item"><?echo $item->name; ?></a>
							<?} ?>
							<?if($item->subItems != null) {?>
								<div class="sub-menu">
									<?
										for($j = 0; $j < count($item->subItems); $j++)
										{
											$sub = $item->subItems[$j];
											if($sub->url != null)
											{?>
												<a href="/admin<?echo $sub->url; ?>"><?echo $sub->name; ?></a>
											<?}else{?>
												<a><?echo $sub->name; ?></a>
											<?}
										}
									?>
								</div>
							<?} ?>
						</td>
					<?}
					?>
					<td class="last"><a href="/admin/auth"><?echo Dictionary::get("exit"); ?></a> <?echo $template['currentUser']->login;?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td class="main-content">
			<div class="buttons-panel"><? include("templates/buttons.phtml");?></div>
			<? include("templates/$partName/$partName.phtml");?>
		</td>
	</tr>
</table>
<script type="text/javascript">
tinyMCE_GZ.init({
	plugins : 'style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,'+ 
        'searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,styler,inlinepopups,safari,pagebreak',
	themes : 'advanced',
	languages : 'ru',
	disk_cache : true,
	debug : false
});
</script>
<script type="text/javascript">
	setTimeout(function(){
		tinyMCE.init({
			styles:{css:"/css/tiny.css", styles:[{name:"my-table", title:"Для таблицы"}]},
			language : 'ru',
			mode : "specific_textareas",
			editor_selector:"richtext",
			theme : "advanced",
			plugins : "safari,pagebreak,style,table,layer,media,advhr,advimage,advlink,preview,iespell,inlinepopups,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,styler",
			theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor",
			theme_advanced_buttons2 : "undo,redo,|,fullscreen,|,preview,removeformat,visualaid,|,cut,copy,paste,pastetext,pasteword,|,bullist,numlist,outdent,indent,blockquote,|,sub,sup,charmap,|,visualchars",
			theme_advanced_buttons3 : "link,unlink,anchor,image,media,code,|,tablecontrols,|,hr,removeformat,|,insertlayer,moveforward,movebackward,absolute",
			theme_advanced_blockformats:"h1,h2,h3",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : "true",
			relative_urls:false
		});
	}, 200);
</script>
</body>
</html>